### ISSUE TITLE
Can not figure out appropriate configuration

### ISSUE THREAD

**Issue by jengweneg** [upcrob/spring-security-otp#1]
Hello , 
I have a spring implementation with the following user-context.xml file that handle user log in
How do i precisely modify it in order to integrate the OTP plugin configuration.
Thanx a lot

---

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
   xmlns:mvc="http://www.springframework.org/schema/mvc"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns:tx="http://www.springframework.org/schema/tx"
        xmlns:context="http://www.springframework.org/schema/context"
        xmlns:security="http://www.springframework.org/schema/security"
        xmlns:oauth="http://www.springframework.org/schema/security/oauth2"
        xsi:schemaLocation="http://www.springframework.org/schema/security/oauth2    
        http://www.springframework.org/schema/security/spring-security-oauth2-2.0.xsd
                http://www.springframework.org/schema/mvc   
        http://www.springframework.org/schema/mvc/spring-mvc-4.1.xsd
                http://www.springframework.org/schema/security 
       http://www.springframework.org/schema/security/spring-security-3.2.xsd
                http://www.springframework.org/schema/beans 
      http://www.springframework.org/schema/beans/spring-beans-4.1.xsd
                http://www.springframework.org/schema/tx 
      http://www.springframework.org/schema/tx/spring-tx-4.1.xsd
                http://www.springframework.org/schema/context 
      http://www.springframework.org/schema/context/spring-context-4.1.xsd">

```
    <security:authentication-manager alias="authenticationManager">
            <security:authentication-provider>
                    <security:jdbc-user-service data-source-ref="dataSource"/>
            </security:authentication-provider>
    </security:authentication-manager>

    <mvc:view-controller path="/login" view-name="login" />

    <security:http disable-url-rewriting="true" use-expressions="true">
            <security:form-login login-page="/login" authentication-failure-url="/login?error=failure" authentication-success-handler-ref="authenticationTimeStampe$
            <security:intercept-url pattern="/authorize" access="hasRole('ROLE_USER')" />
            <security:intercept-url pattern="/**" access="permitAll" />
            <security:custom-filter ref="authRequestFilter" after="SECURITY_CONTEXT_FILTER" />
            <security:custom-filter ref="resourceServerFilter" before="PRE_AUTH_FILTER" />
            <security:logout logout-url="/logout" />
            <security:anonymous />
            <security:expression-handler ref="oauthWebExpressionHandler" />
            <security:headers>
                    <security:frame-options policy="DENY" />
            </security:headers>
            <security:csrf />
    </security:http>
```

</beans>

**Comment by upcrob** [comment]
Have a look at the sample app, here: https://github.com/upcrob/spring-security-otp-test

That will give you some idea of how the components fit together and how they can be used in the context of your application.

**Comment by jengweneg** [comment]
Hello,
Yes i did but the syntax is different to that of my file and i am lost.
Could you have a quick look please?
Thanx

**Comment by jengweneg** [comment]
Il actually already have an authentication system that i want to use
