### ISSUE TITLE
Implementing OtpValidationFilter

### ISSUE THREAD

**Issue by tayfunyasar** [upcrob/spring-security-otp#2]
Hello,

How should I implement OtpValidationFilter in java config?

Here it is SecurityConfig.java

```
@Override
	protected void configure(HttpSecurity http) throws Exception {
..
http.addFilterAt(otpValidationFilter(), UsernamePasswordAuthenticationFilter.class);

		http.addFilterAfter(customOtpValidationFilter(), UsernamePasswordAuthenticationFilter.class);
...
}
```
```
@Bean
	public OtpValidationFilter customOtpValidationFilter() {
		return new OtpValidationFilter(tokenStore(), "/validate", "private", "login?error");
	}
```

How to configure that filter?

**Comment by upcrob** [comment]
The OtpValidationFilter contstructor takes 4 arguments:
```java
public OtpValidationFilter(Tokenstore tokenstore, String endpoint, String successUrl, String failureUrl)
```
* tokenstore is is the Tokenstore implementation being used to cache tokens.
* endpoint is the path that the filter should listen on (validation requests should be posted to this endpoint.
* successUrl is where the user should be redirected if the token was valid
* failureUrl is where the user should be redirected if the token was invalid

This application may give you some idea of how things fit together as a whole: https://github.com/upcrob/spring-security-otp-test

Keep in mind, however, that these properties will largely depend upon your particular application and how it is architected.

**Comment by tayfunyasar** [comment]
Thanks! It was about my Redis configuration. My beans were injected correctly as u said.
